//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioWebsite
{
    public partial class admin
    {
    /// <summary>
    /// rptAdminProjects control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Repeater rptAdminProjects;

    /// <summary>
    /// rptAdminCertifications control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Repeater rptAdminCertifications;
    }
}
