//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioWebsite {
    public partial class test {
        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}
